import { Word } from "./models"

export const wordsCards: Word[] = [
  { "word": "awkward", "translation": "незручний, недоречний" },
  { "word": "brag", "translation": "хвалитися" },
  { "word": "clumsy", "translation": "незграбний" },
  { "word": "dizzy", "translation": "запаморочений" },
  { "word": "echo", "translation": "відлуння" },
  { "word": "frown", "translation": "хмуритись" },
  { "word": "giggle", "translation": "хіхікати" },
  { "word": "hollow", "translation": "порожнистий" },
  { "word": "itch", "translation": "свербіти" },
  { "word": "juggle", "translation": "жонглювати" },
  { "word": "kneel", "translation": "ставати на коліна" },
  { "word": "leak", "translation": "протікати" },
  { "word": "mumble", "translation": "бурмотіти" },
  { "word": "nudge", "translation": "підштовхувати ліктем" },
  { "word": "obey", "translation": "підкорятися" },
  { "word": "peek", "translation": "зазирнути" },
  { "word": "quirky", "translation": "чудний, дивакуватий" },
  { "word": "rumor", "translation": "чутка" },
  { "word": "snore", "translation": "хропіти" },
  { "word": "tame", "translation": "приручити" },
  { "word": "urge", "translation": "сильне бажання, спонукати" },
  { "word": "vague", "translation": "нечіткий, розпливчастий" },
  { "word": "whisper", "translation": "шепотіти" },
  { "word": "yawn", "translation": "позіхати" },
  { "word": "zip", "translation": "застібка-блискавка, застібати" },
  { "word": "applause", "translation": "оплески" },
  { "word": "blush", "translation": "червоніти" },
  { "word": "crawl", "translation": "повзати" },
  { "word": "drizzle", "translation": "мряка, накрапати" },
  { "word": "envy", "translation": "заздрість" },
  { "word": "flip", "translation": "перекидати" },
  { "word": "glow", "translation": "світитися" },
  { "word": "hesitate", "translation": "вагатися" },
  { "word": "inflate", "translation": "надувати" },
  { "word": "jam", "translation": "затор, варення, застрягати" },
  { "word": "knock", "translation": "стукати" },
  { "word": "lean", "translation": "нахилятися, худий" },
  { "word": "moan", "translation": "стонати" },
  { "word": "nod", "translation": "кивати головою" },
  { "word": "owe", "translation": "бути винним" },
  { "word": "poke", "translation": "тикати" },
  { "word": "quote", "translation": "цитата, цитувати" },
  { "word": "rip", "translation": "рвати" },
  { "word": "scratch", "translation": "дряпати" },
  { "word": "tickle", "translation": "лоскотати" },
  { "word": "unwrap", "translation": "розгортати" },
  { "word": "vanish", "translation": "зникати" },
  { "word": "wander", "translation": "блукати" },
  { "word": "yell", "translation": "кричати" },
  { "word": "zoom", "translation": "наближати, пролетіти швидко" },
  { "word": "amuse", "translation": "розважати" },
  { "word": "bounce", "translation": "підстрибувати" },
  { "word": "clue", "translation": "підказка, зачіпка" },
  { "word": "doubt", "translation": "сумнів" },
  { "word": "explode", "translation": "вибухати" },
  { "word": "fade", "translation": "в'янути, зникати" },
  { "word": "grin", "translation": "усміхатися широко" },
  { "word": "hover", "translation": "зависати" },
  { "word": "itchy", "translation": "той, що свербить" },
  { "word": "joke", "translation": "жарт" },
  { "word": "kick", "translation": "бити ногою" },
  { "word": "limp", "translation": "кульгати" },
  { "word": "melt", "translation": "танути" },
  { "word": "nasty", "translation": "огидний, злий" },
  { "word": "odd", "translation": "дивний" },
  { "word": "panic", "translation": "панікувати" },
  { "word": "rescue", "translation": "рятувати" },
  { "word": "sigh", "translation": "зітхати" },
  { "word": "tremble", "translation": "тремтіти" },
  { "word": "unwrap", "translation": "розгортати" },
  { "word": "waste", "translation": "марнувати" },
  { "word": "yearn", "translation": "тужити, сильно прагнути" },
  { "word": "absorb", "translation": "вбирати, поглинати" },
  { "word": "bark", "translation": "гавкати, кора дерева" },
  { "word": "crash", "translation": "тріск, аварія, зіштовхнутись" },
  { "word": "dare", "translation": "насмілюватися" },
  { "word": "embrace", "translation": "обіймати" },
  { "word": "flick", "translation": "щиголь, різкий рух" },
  { "word": "glimpse", "translation": "поглянути побіжно" },
  { "word": "hum", "translation": "наспівувати" },
  { "word": "ignore", "translation": "ігнорувати" },
  { "word": "jelly", "translation": "желе" },
  { "word": "knead", "translation": "місити тісто" },
  { "word": "leap", "translation": "стрибок, стрибати" },
  { "word": "mystery", "translation": "таємниця" },
  { "word": "nap", "translation": "дрімота" },
  { "word": "observe", "translation": "спостерігати" },
  { "word": "puzzle", "translation": "головоломка" },
  { "word": "resist", "translation": "чинити опір" },
  { "word": "shiver", "translation": "тремтіти від холоду" },
  { "word": "trap", "translation": "пастка" },
  { "word": "unwrap", "translation": "розгортати" },
  { "word": "victim", "translation": "жертва" },
  { "word": "weep", "translation": "плакати" },
  { "word": "zipper", "translation": "блискавка (застібка)" },
  { "word": "zone", "translation": "зона" }
]
