import { Word } from "../models/models"




export const testDataC1: Word[] = [
  { "word": "awkward", "translation": "незручний, недоречний" },
  { "word": "brag", "translation": "хвалитися" },
  { "word": "clumsy", "translation": "незграбний" },
  { "word": "dizzy", "translation": "запаморочений" },
  { "word": "echo", "translation": "відлуння" },
  { "word": "frown", "translation": "хмуритись" },
  { "word": "giggle", "translation": "хіхікати" },
  { "word": "hollow", "translation": "порожнистий" },
  { "word": "itch", "translation": "свербіти" },
  { "word": "juggle", "translation": "жонглювати" },
  { "word": "kneel", "translation": "ставати на коліна" },
  { "word": "leak", "translation": "протікати" },
  { "word": "mumble", "translation": "бурмотіти" },
  { "word": "nudge", "translation": "підштовхувати ліктем" },
  { "word": "obey", "translation": "підкорятися" },
  { "word": "peek", "translation": "зазирнути" },
  { "word": "quirky", "translation": "чудний, дивакуватий" },
  { "word": "rumor", "translation": "чутка" },
  { "word": "snore", "translation": "хропіти" },
  { "word": "tame", "translation": "приручити" },
  { "word": "urge", "translation": "сильне бажання, спонукати" },
  { "word": "vague", "translation": "нечіткий, розпливчастий" },
  { "word": "whisper", "translation": "шепотіти" },
  { "word": "yawn", "translation": "позіхати" },
  { "word": "zip", "translation": "застібка-блискавка, застібати" },
  { "word": "applause", "translation": "оплески" },
  { "word": "blush", "translation": "червоніти" },
  { "word": "crawl", "translation": "повзати" },
  { "word": "drizzle", "translation": "мряка, накрапати" },
  { "word": "envy", "translation": "заздрість" },
  { "word": "flip", "translation": "перекидати" },
  { "word": "glow", "translation": "світитися" },
  { "word": "hesitate", "translation": "вагатися" },
  { "word": "inflate", "translation": "надувати" },
  { "word": "jam", "translation": "затор, варення, застрягати" },
  { "word": "knock", "translation": "стукати" },
  { "word": "lean", "translation": "нахилятися, худий" },
  { "word": "moan", "translation": "стонати" },
  { "word": "nod", "translation": "кивати головою" },
  { "word": "owe", "translation": "бути винним" },
  { "word": "poke", "translation": "тикати" },
  { "word": "quote", "translation": "цитата, цитувати" },
  { "word": "rip", "translation": "рвати" },
  { "word": "scratch", "translation": "дряпати" },
  { "word": "tickle", "translation": "лоскотати" },
  { "word": "unwrap", "translation": "розгортати" },
  { "word": "vanish", "translation": "зникати" },
  { "word": "wander", "translation": "блукати" },
  { "word": "yell", "translation": "кричати" },
  { "word": "zoom", "translation": "наближати, пролетіти швидко" },
  { "word": "amuse", "translation": "розважати" },
  { "word": "bounce", "translation": "підстрибувати" },
  { "word": "clue", "translation": "підказка, зачіпка" },
  { "word": "doubt", "translation": "сумнів" },
  { "word": "explode", "translation": "вибухати" },
  { "word": "fade", "translation": "в'янути, зникати" },
  { "word": "grin", "translation": "усміхатися широко" },
  { "word": "hover", "translation": "зависати" },
  { "word": "itchy", "translation": "той, що свербить" },
  { "word": "joke", "translation": "жарт" },
  { "word": "kick", "translation": "бити ногою" },
  { "word": "limp", "translation": "кульгати" },
  { "word": "melt", "translation": "танути" },
  { "word": "nasty", "translation": "огидний, злий" },
  { "word": "odd", "translation": "дивний" },
  { "word": "panic", "translation": "панікувати" },
  { "word": "rescue", "translation": "рятувати" },
  { "word": "sigh", "translation": "зітхати" },
  { "word": "tremble", "translation": "тремтіти" },
  { "word": "unwrap", "translation": "розгортати" },
  { "word": "waste", "translation": "марнувати" },
  { "word": "yearn", "translation": "тужити, сильно прагнути" },
  { "word": "absorb", "translation": "вбирати, поглинати" },
  { "word": "bark", "translation": "гавкати, кора дерева" },
  { "word": "crash", "translation": "тріск, аварія, зіштовхнутись" },
  { "word": "dare", "translation": "насмілюватися" },
  { "word": "embrace", "translation": "обіймати" },
  { "word": "flick", "translation": "щиголь, різкий рух" },
  { "word": "glimpse", "translation": "поглянути побіжно" },
  { "word": "hum", "translation": "наспівувати" },
  { "word": "ignore", "translation": "ігнорувати" },
  { "word": "jelly", "translation": "желе" },
  { "word": "knead", "translation": "місити тісто" },
  { "word": "leap", "translation": "стрибок, стрибати" },
  { "word": "mystery", "translation": "таємниця" },
  { "word": "nap", "translation": "дрімота" },
  { "word": "observe", "translation": "спостерігати" },
  { "word": "puzzle", "translation": "головоломка" },
  { "word": "resist", "translation": "чинити опір" },
  { "word": "shiver", "translation": "тремтіти від холоду" },
  { "word": "trap", "translation": "пастка" },
  { "word": "unwrap", "translation": "розгортати" },
  { "word": "victim", "translation": "жертва" },
  { "word": "weep", "translation": "плакати" },
  { "word": "zipper", "translation": "блискавка (застібка)" },
  { "word": "zone", "translation": "зона" }
]


export const testDataV1: Word[] = [
  { word: "rainbow", translation: "веселка" },
  { word: "stick", translation: "палиця" },
  { word: "gun", translation: "пістолет" },
  { word: "war", translation: "війна" },
  { word: "biology", translation: "біологія" },
  { word: "monster", translation: "монстр" },
  { word: "rocket", translation: "ракета" },
  { word: "cave", translation: "печера" },
  { word: "pirate", translation: "пірат" },
  { word: "crown", translation: "корона" },
  { word: "king", translation: "король" },
  { word: "queen", translation: "королева" },
  { word: "zombie", translation: "зомбі" },
  { word: "laser", translation: "лазер" },
  { word: "robot", translation: "робот" },
  { word: "prison", translation: "в'язниця" },
  { word: "planet", translation: "планета" },
  { word: "alien", translation: "прибулець" },
  { word: "explosion", translation: "вибух" },
  { word: "storm", translation: "буря" },
  { word: "vampire", translation: "вампір" },
  { word: "castle", translation: "замок" },
  { word: "dragon", translation: "дракон" },
  { word: "forest", translation: "ліс" },
  { word: "fire", translation: "вогонь" },
  { word: "ice", translation: "лід" },
  { word: "ghost", translation: "привид" },
  { word: "sword", translation: "меч" },
  { word: "shield", translation: "щит" },
  { word: "magic", translation: "магія" },
  { word: "witch", translation: "відьма" },
  { word: "wizard", translation: "чарівник" },
  { word: "treasure", translation: "скарб" },
  { word: "map", translation: "карта" },
  { word: "jungle", translation: "джунглі" },
  { word: "volcano", translation: "вулкан" },
  { word: "dinosaur", translation: "динозавр" },
  { word: "cannon", translation: "гармата" },
  { word: "trap", translation: "пастка" },
  { word: "tank", translation: "танк" },
  { word: "helmet", translation: "шолом" },
  { word: "soldier", translation: "солдат" },
  { word: "army", translation: "армія" },
  { word: "police", translation: "поліція" },
  { word: "prince", translation: "принц" },
  { word: "princess", translation: "принцеса" },
  { word: "bridge", translation: "міст" },
  { word: "river", translation: "річка" },
  { word: "cliff", translation: "скеля" },
  { word: "cave", translation: "печера" }
];


export const testData: Word[] = [
  { word: "blood", translation: "кров" },
  { word: "hospital", translation: "лікарня" },
  { word: "school", translation: "школа" },
  { word: "teacher", translation: "вчитель" },
  { word: "knife", translation: "ніж" },
  { word: "hammer", translation: "молоток" },
  { word: "nail", translation: "цвях" },
  { word: "glove", translation: "рукавичка" },
  { word: "socks", translation: "шкарпетки" },
  { word: "pants", translation: "штани" },
  { word: "shirt", translation: "сорочка" },
  { word: "coat", translation: "пальто" },
  { word: "backpack", translation: "рюкзак" },
  { word: "train", translation: "потяг" },
  { word: "airport", translation: "аеропорт" },
  { word: "ticket", translation: "квиток" },
  { word: "window", translation: "вікно" },
  { word: "mirror", translation: "дзеркало" },
  { word: "soap", translation: "мило" },
  { word: "toilet", translation: "туалет" },
  { word: "kitchen", translation: "кухня" },
  { word: "spoon", translation: "ложка" },
  { word: "fork", translation: "виделка" },
  { word: "knife", translation: "ніж" },
  { word: "plate", translation: "тарілка" },
  { word: "cup", translation: "чашка" },
  { word: "camera", translation: "камера" },
  { word: "photo", translation: "фото" },
  { word: "movie", translation: "фільм" },
  { word: "actor", translation: "актор" },
  { word: "singer", translation: "співак" },
  { word: "band", translation: "гурт" },
  { word: "stage", translation: "сцена" },
  { word: "light", translation: "світло" },
  { word: "dark", translation: "темрява" },
  { word: "shadow", translation: "тінь" },
  { word: "hole", translation: "дірка" },
  { word: "ladder", translation: "драбина" },
  { word: "roof", translation: "дах" },
  { word: "floor", translation: "підлога" },
  { word: "ceiling", translation: "стеля" },
  { word: "key", translation: "ключ" },
  { word: "lock", translation: "замок" },
  { word: "chain", translation: "ланцюг" },
  { word: "rope", translation: "мотузка" },
  { word: "button", translation: "кнопка, ґудзик" },
  { word: "string", translation: "нитка, струна" },
  { word: "hat", translation: "капелюх" },
  { word: "helmet", translation: "шолом" },
  { word: "glasses", translation: "окуляри" },
  { word: "bottle", translation: "пляшка" },
  { word: "box", translation: "коробка" },
  { word: "bag", translation: "сумка" },
  { word: "ball", translation: "м’яч" },
  { word: "board", translation: "дошка" },
  { word: "chalk", translation: "крейда" },
  { word: "paper", translation: "папір" },
  { word: "letter", translation: "лист (паперовий)" },
  { word: "stamp", translation: "марка" },
  { word: "envelope", translation: "конверт" },
  { word: "money", translation: "гроші" },
  { word: "coin", translation: "монета" },
  { word: "wallet", translation: "гаманець" },
  { word: "pocket", translation: "кишеня" },
  { word: "toy", translation: "іграшка" },
  { word: "doll", translation: "лялька" },
  { word: "car", translation: "авто" },
  { word: "bicycle", translation: "велосипед" },
  { word: "motorcycle", translation: "мотоцикл" },
  { word: "boat", translation: "човен" },
  { word: "submarine", translation: "підводний човен" },
  { word: "whale", translation: "кит" },
  { word: "shark", translation: "аку́ла" },
  { word: "lion", translation: "лев" },
  { word: "tiger", translation: "тигр" },
  { word: "bear", translation: "ведмідь" },
  { word: "snake", translation: "змія" },
  { word: "spider", translation: "павук" },
  { word: "ant", translation: "мураха" },
  { word: "bee", translation: "бджола" },
  { word: "bird", translation: "птах" },
  { word: "egg", translation: "яйце" },
  { word: "tree", translation: "дерево" },
  { word: "branch", translation: "гілка" },
  { word: "leaf", translation: "листок" },
  { word: "grass", translation: "трава" },
  { word: "hill", translation: "пагорб" },
  { word: "mountain", translation: "гора" },
  { word: "desert", translation: "пустеля" },
  { word: "snow", translation: "сніг" },
  { word: "rain", translation: "дощ" },
  { word: "cloud", translation: "хмара" },
  { word: "wind", translation: "вітер" },
  { word: "sun", translation: "сонце" },
  { word: "moon", translation: "місяць" },
    { word: "star", translation: "зірка" },
    { word: "space", translation: "космос" },
  { word: "doctor", translation: "лікар" },
  { word: "nurse", translation: "медсестра" },
  { word: "patient", translation: "пацієнт" },
  { word: "medicine", translation: "ліки" },
  { word: "pain", translation: "біль" },
  { word: "fever", translation: "жар, температура" },
  { word: "cold", translation: "застуда" },
  { word: "cough", translation: "кашель" },
  { word: "head", translation: "голова" },
  { word: "arm", translation: "рука" },
  { word: "leg", translation: "нога" },
  { word: "hand", translation: "долоня" },
  { word: "foot", translation: "ступня" },
  { word: "eye", translation: "око" },
  { word: "ear", translation: "вухо" },
  { word: "nose", translation: "ніс" },
  { word: "mouth", translation: "рот" },
  { word: "tooth", translation: "зуб" },
  { word: "back", translation: "спина" },
  { word: "heart", translation: "серце" },
  { word: "blood", translation: "кров" },
  { word: "skin", translation: "шкіра" },
  { word: "bone", translation: "кістка" },
  { word: "brain", translation: "мозок" },
  { word: "game", translation: "гра" },
  { word: "level", translation: "рівень" },
  { word: "hero", translation: "герой" },
  { word: "enemy", translation: "ворог" },
  { word: "fight", translation: "бійка, битва" },
  { word: "win", translation: "перемагати" },
  { word: "lose", translation: "програвати" },
  { word: "score", translation: "рахунок" },
  { word: "goal", translation: "гол" },
  { word: "team", translation: "команда" },
  { word: "match", translation: "матч" },
  { word: "race", translation: "перегони" },
  { word: "swim", translation: "плавати" },
  { word: "run", translation: "бігти" },
  { word: "jump", translation: "стрибати" },
  { word: "throw", translation: "кидати" },
  { word: "catch", translation: "ловити" },
  { word: "ball", translation: "м’яч" },
  { word: "bat", translation: "бита (або кажан)" },
  { word: "glove", translation: "рукавичка" },
  { word: "net", translation: "сітка" },
  { word: "referee", translation: "суддя (в спорті)" },
  { word: "whistle", translation: "свисток" },
  { word: "uniform", translation: "форма" },
  { word: "medal", translation: "медаль" },
  { word: "trophy", translation: "трофей" },
  { word: "fan", translation: "вболівальник" },
  { word: "stadium", translation: "стадіон" },
  { word: "ticket", translation: "квиток" },
  { word: "seat", translation: "місце" },
  { word: "row", translation: "ряд" },
  { word: "crowd", translation: "натовп" },
  { word: "cheer", translation: "підбадьорювати, кричати" },
  { word: "flag", translation: "прапор" },
  { word: "country", translation: "країна" },
  { word: "city", translation: "місто" },
  { word: "village", translation: "село" },
  { word: "street", translation: "вулиця" },
  { word: "road", translation: "дорога" },
  { word: "car", translation: "автомобіль" },
  { word: "bus", translation: "автобус" },
  { word: "truck", translation: "вантажівка" },
  { word: "motorbike", translation: "мотоцикл" },
  { word: "bicycle", translation: "велосипед" },
  { word: "helmet", translation: "шолом" },
  { word: "seatbelt", translation: "ремінь безпеки" },
  { word: "wheel", translation: "колесо" },
  { word: "engine", translation: "двигун" },
  { word: "fuel", translation: "паливо" },
  { word: "gas", translation: "бензин" },
  { word: "garage", translation: "гараж" },
  { word: "parking", translation: "паркінг" },
  { word: "traffic", translation: "трафік, рух" },
  { word: "light", translation: "світло" },
  { word: "crossing", translation: "пішохідний перехід" },
  { word: "sidewalk", translation: "тротуар" },
  { word: "corner", translation: "кут" },
  { word: "bridge", translation: "міст" },
  { word: "river", translation: "річка" },
  { word: "lake", translation: "озеро" },
  { word: "sea", translation: "море" },
  { word: "ocean", translation: "океан" },
  { word: "beach", translation: "пляж" },
  { word: "sand", translation: "пісок" },
  { word: "wave", translation: "хвиля" },
  { word: "swim", translation: "плавати" },
  { word: "boat", translation: "човен" },
  { word: "ship", translation: "корабель" },
  { word: "sail", translation: "вітрило, плисти під вітрилом" },
  { word: "island", translation: "острів" },
  { word: "sun", translation: "сонце" },
  { word: "heat", translation: "спека" },
  { word: "umbrella", translation: "парасолька" }
];

